### ISSUE TITLE
Rename 'opentf' binary to 'tf'

### ISSUE THREAD

**Issue by ErikHumphrey** [opentffoundation/opentf#273]
### Summary

Rename the `opentf` binary (executable, command) to simply `tf`, while leaving the project name as it is (OpenTF).  
Like OpenOffice and LibreOffice, `opentf` sounds like less cool as a command `terraform`, so we should at least make the binary `tf` while we can.

### Problem statement

OpenTF is run using `opentf` instead of `terraform`. As a drop-in replacement for `terraform`, you can rename the binary or alias it as needed. But `tf` would be a lot shorter and friendlier.

Naming the CLI tool command/binary itself is important, and it's impossible to do later in the project, so we should decide now. `tf` is short and simple, and more appealing than `opentf`. If we want people using OpenTF, `tf` will attract users more than both `opentf` and perhaps even `terraform`.

Users will likely choose `terraform` over `opentf` because `terraform` sounds smoother, whereas `opentf` sounds like an alternative. Open, yes, but an alternative, like OpenOffice or LibreOfifce. `tf` does not necessarily sound like an alternative.

Compare [`youtube-dl`](https://github.com/ytdl-org/youtube-dl) (rarely abbreviated as `ytdl`) and its better alternative, [`yt-dlp`](https://github.com/yt-dlp/yt-dlp). Not a 1:1 example, but there are other examples with and without the word "open" out there.

### User-facing description

To use OpenTF, you can use `tf` commands just as you would `terraform` commands:

#### Main commands

* `tf init`
* `tf validate`
* `tf plan`
* `tf apply`
* `tf destroy`

<details>
  <summary>All other commands</summary>
  
  * `tf console`
  * `tf fmt`
  * `tf force-unlock`
  * `tf get`
  * `tf graph`
  * `tf import`
  * `tf login`
  * `tf logout`
  * `tf metadata`
  * `tf output`
  * `tf providers`
  * `tf refresh`
  * `tf show`
  * `tf state`
  * `tf taint`
  * `tf test`
  * `tf untaint`
  * `tf version`
  * `tf workspace`

</details>

### Technical description

We will need to rename most things that reference the binary. Most changes would be in the build scripts and documentation. There is no need to rename most other references to `opentf` in the code, as they pertain to the project name.

For example, something like `bin/opentf` should be changed to `bin/tf`. We would not rename the `opentf_1.5.6.darwin_arm64.zip` archive, but the enclosed binary would simply be `tf` so that that `tf` is found in their PATH.

| Terraform                          | OpenTF equivalent               |
| :--------------------------------- | :------------------------------ |
| `terraform_1.5.6_darwin_arm64.zip` | `opentf_1.5.6_darwin_arm64.zip` |
| `terraform`                        | `tf`                            |
| `terraform plan`                   | `tf plan`                       |
| `terraform apply`                  | `tf apply`                      |
| `terraform destroy`                | `tf destroy`                    |
| `main.tf`                          | `main.tf`                       |

### Rationale

* `tf` is very short for a CLI tool name.
  * Quick to type (2 characters vs. 6 characters)
  * Quick to say (2 syllables vs. 4 syllables).
* `tf` matches the filename extension for OpenTF modules ("TF files"), `.tf`.
* `tf` is a common abbreviation for Terraform, but not trademarked.
* Some developers have already aliased `tf` to `terraform` for ease of use.
* `opentf` is unintuitive, other than that it matches the name of the project.
* The `open` part of `opentf` is extra / not necessary to know when running it as a CLI tool.
* Keeps running OpenTF commands (or "`tf`  commands") short and simple.
* Users would likely choose `terraform` over `opentf` because `terraform` sounds smoother, whereas `opentf` sounds like an alternative. Open, yes, but an alternative, like OpenOffice or LibreOfifce. `tf` does not necessarily sound like an alternative.

### Downsides

* `opentf` is already shorter than `terraform`.
* `tf` doesn't fully match the project name,`opentf`.
* `tf` could be confused for Terraform.
* `tf` makes people think "Terraform" more than "OpenTF", but "OpenTF" is not intended to hide that it is Terraform
* Terraform is a trademark (however, TF is not).

**Comment by ppabis** [comment]
What I use is simply an alias in `~/.profile`, but as a binary name it can be confusing. There's `df`, there's `tr`, which are coreutils, so two letters should be reserved to some degree.

**Comment by mikelolasagasti** [comment]
Debian/Ubuntu already have a package named `tf`:

https://packages.debian.org/sid/tf
https://packages.ubuntu.com/kinetic/tf

Package is managed by Debian's Alternatives System:

~~~
# which tf
/usr/bin/tf

# ls -l /usr/bin/tf 
lrwxrwxrwx. 1 root root 20 Sep  6 09:24 /usr/bin/tf -> /etc/alternatives/tf

# update-alternatives --display tf
tf - auto mode
  link best version is /usr/games/tf
  link currently points to /usr/games/tf
  link tf is /usr/bin/tf
  slave tf.1.gz is /usr/share/man/man1/tf.1.gz
/usr/games/tf - priority 50
  slave tf.1.gz: /usr/share/man/man1/tf4.1.gz
~~~

Package `opentf` could provide an alternative `tf` and _iiuc_ it should be enough.

In Fedora  the same package is named `tinyfugue`, but provides `/usr/bin/tf` binary:

~~~
# dnf whatprovides -C /usr/bin/tf
Last metadata expiration check: 1:28:26 ago on 23-09-06 09:50:24.
tinyfugue-5.0-0.108.b8.fc38.x86_64 : A MU* client
Repo        : fedora
Matched from:
Filename    : /usr/bin/tf
~~~

Packaging guidelines require `Conflicting package names MUST be resolved`:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Conflicts/#_conflicting_package_names

This means that if OpenTF is packaged for Fedora natively, it would require either renaming `tf` binary to `opentf` or to discuss with `tinyfugue` maintainer about changing the name in that package.

I haven't checked other distributions, but they may be in a similar situation. A list of distributions that have `tinyfugue` packaged: 

https://repology.org/project/tinyfugue/versions

**Comment by roni-frantchi** [comment]
Hey everyone thanks very much for the feedback and discussion!  
There are two more issues opened that kick off a discussion very similar to this one, and so we've created https://github.com/opentffoundation/opentf/issues/296 to keep the discussions going in one place.  

We'd love to keep this discussion going there! 🙏

**Comment by julian-alarcon** [comment]
So, opentofu or tofu for the binary?
I like the simple tofu
```
tofu apply
tofu plan
tofu destroy
```
