### ISSUE TITLE
link to Slack workspace does not work on mobile (works only in desktop)

### ISSUE THREAD

**Issue by ohad1282** [opentffoundation/opentf#275]
clicking "[Join our Slack community!](https://join.slack.com/t/slack-9uv6202/shared_invite/zt-22ifsm1t2-AF6cL0cOdzivP8E~4deDJA)" from the Readme fails if you are on mobile. Happened to me and to another user that contacted me here - https://www.linkedin.com/feed/update/urn:li:activity:7104846815975403520?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7104846815975403520%2C7104858868148523009%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287104858868148523009%2Curn%3Ali%3Aactivity%3A7104846815975403520%29

**Comment by xinity** [comment]
@ohad1282 I'm the one who reported to you the issue.
You can update the issue to make it more readable I'd say 😁
