### ISSUE TITLE
The branding (logo and project name) is not distinct enough from Terraform's

### ISSUE THREAD

**Issue by dylanmtaylor** [opentffoundation/opentf#276]
### Summary

I love this project and the fact that Terraform is being maintained as a fully open source fork, but without distinct enough branding, it opens up OpenTF and its contributors to a lawsuit from Hashicorp.

### Problem Statement

Avoiding contention with Hashicorp's lawyers

### User-facing description

N/A

### Technical Description

N/A

### Rationale and alternatives

Not having a distinct name and logo is a major concern to users and contributors.

**Comment by DicsyDel** [comment]
Hi @dylanmtaylor,

Please check my comment here: https://github.com/opentffoundation/opentf/issues/273#issuecomment-1706947318

As soon as we finalize the name and clear all legal aspects of it, we will review branding again.

Regards,
Igor

**Comment by mikebobadilla** [comment]
They should call it hashbrows.

**Comment by pauldraper** [comment]
I'd name it something cloud-y.

Like "Stratus"

**Comment by jebotz** [comment]
"Cloudy" is not right.  It's not about the cloud, it's about infrastructure, cloud or otherwise.

**Comment by ppabis** [comment]
There's always *glTF*, so you can name the project *Cloud Transmission Format*, `ctf` or `openctf`

**Comment by graemechristie** [comment]
I've always though "FreeForm" was a no brainer ..

**Comment by ppabis** [comment]
> I've always though "FreeForm" was a no brainer ..

Apple already has such app :/

**Comment by roni-frantchi** [comment]
Hey everyone thanks very much for the feedback and discussion!  
There are two more issues opened that kick off a discussion very similar to this one, and so we've created https://github.com/opentffoundation/opentf/issues/296 to keep the discussions going in one place.  

We'd love to keep this discussion going there! 🙏
