### ISSUE TITLE
Add license checks on dependencies

### ISSUE THREAD

**Issue by pdecat** [opentffoundation/opentf#305]
### OpenTF Version

```shell
# opentf version
OpenTF v1.6.0-dev
on linux_amd64
```

### Use Cases

As mentioned in [this Slack thread](https://opentfcommunity.slack.com/archives/C05RKE7PS72/p1693983939719419), license checks in pre-commit hooks, Makefile and CI should be added to ensure OpenTF does not depend on non open-source dependencies.

### Attempted Solutions

Searched for such checks in the build chain, and did not find any.

### Proposal

Use https://github.com/goph/licensei for license checks.

### References

Sample configuration https://github.com/bank-vaults/bank-vaults/blob/main/.licensei.toml

**Comment by pdecat** [comment]
Started working on this.

**Comment by cube2222** [comment]
Thanks for creating the issue @pdecat, assigned it to you and looking forward to the PR!
