### ISSUE TITLE
Deprecate io/ioutil Project Wide

### ISSUE THREAD

**Issue by alrs** [opentffoundation/opentf#313]
### OpenTF Version

```shell
.
```

### Use Cases

.

### Attempted Solutions

.

### Proposal

`io/ioutil` was deprecated in Go 1.16, and would be a good first target for replacing deprecated dependencies.

### References

.

**Comment by eranelbaz** [comment]
Hey @alrs 
Thank you for the contribution here!
Can you please alter the description and write the relevant folders you are working on?
so we'll know the "progress bar" for this issue

**Comment by adrianmester** [comment]
these are the ones not currently merged into `main`

```
- [ ] `internal/command` - #318 
- [ ] `internal/communicator`
- [ ] `internal/configs`
- [ ] `internal/copy`
- [ ] `internal/depsfile`
- [ ] `internal/e2e`
- [ ] `internal/getproviders`
- [ ] `internal/initwd`
- [ ] `internal/lang`
- [ ] `internal/legacy`
- [ ] `internal/modsdir`
- [ ] `internal/plans`
- [ ] `internal/plugin`
- [ ] `internal/providercache`
- [ ] `internal/registry`
- [ ] `internal/replacefile`
- [ ] `internal/states` - #320
```

**Comment by eranelbaz** [comment]
Thank you @adrianmester !
Please if you take a package write it here to minimize duplicate work :)

**Comment by jay-dee7** [comment]
Hey @eranelbaz @alrs,
I'm willing to take up the following, if that's alright? I'll submit individual PRs for them ASAP
- [ ] `internal/plugin`
- [ ] `internal/plans`
- [ ] `internal/registry`
- [ ] `internal/replacefile`
