### ISSUE TITLE
Rename the module to match the repository name

### ISSUE THREAD

**Issue by kislerdm** [opentffoundation/opentf#323]
## Problem

The go module's name is not in line with the repo name, which is not in line with best practices.

## Proposed Solution

Rename the gomodule to `github.com/opentffoundation/opentf` instead of `github.com/placeholderplaceholderplaceholder/opentf`.

**Comment by Yantrio** [comment]
Hi @kislerdm, 

Thanks for raising this! 🙌 

We're actually holding off on changing all of the instances of placeholder until OpenTF has a finalized name.

We're currently tracking the name change here: https://github.com/opentffoundation/opentf/issues/296#issuecomment-1708333906

And there is an issue for this here: https://github.com/opentffoundation/opentf/issues/165

These issues combined should cover what is described here.
