### ISSUE TITLE
Fix the links in the documentation and ci pipeline definitions

### ISSUE THREAD

**Issue by kislerdm** [opentffoundation/opentf#324]
## Problem

Some of the links are broken. For example, see [CONTRIBUTING.md](https://github.com/opentffoundation/opentf/blob/main/CONTRIBUTING.md#working-on-the-code), the link to the .go-version file.

## Proposed solution

- Replace URLs with files in md;
- Replace `github.com/placeholderplaceholderplaceholder/opentf` with `github.com/opentffoundation/opentf` in CI definitions

**Comment by cube2222** [comment]
Hey, makes sense, thanks for creating the issue @kislerdm!
