### ISSUE TITLE
Automatically delete head branches

### ISSUE THREAD

**Issue by rumenvasilev** [opentffoundation/opentf#360]
### OpenTF Version

```shell
n/a
```

### Use Cases

n/a

### Attempted Solutions

n/a

### Proposal

I normally configure 'Automatically delete head branches' on any repository I work on. Especially on repos that are heavily used by multiple contributors. Branches are starting to pile up and not getting cleaned up.
Did you intentionally left that setting unchecked?

**Comment by cube2222** [comment]
Thanks for pointing it out @rumenvasilev! I've updated it to automatically delete branches now, thanks!
