### ISSUE TITLE
Make Errors Full Types Before internal/ Migration

### ISSUE THREAD

**Issue by alrs** [opentffoundation/opentf#363]
### OpenTF Version

```shell
.
```

### Use Cases

Custom errors created with `errors.New()` or `format.Errorf()` cannot be used meaningfully in type assertions. This makes debugging harder than it needs to be in our local case, and makes life harder for external projects that want to use parts of OpenTF as libraries.

### Attempted Solutions

.

### Proposal

I propose that we update custom errors to be types instead of just variables. We will then be able to use `errors.Is()` or a type assertion in tests instead of brittle string comparisons. We will no longer see so many errors come in as `*errors.errorString`.

I assume that some or all of the code in OpenTF will be moved out of `internal` at some point, so we have a window of time until then to make changes to the internal API before we become an upstream dependency. Now is a good time to improve error handling.  Multiple pull requests can be pointed at this issue.

**Comment by eranelbaz** [comment]
Hey @alrs can you please explain how this will help with debugging?

**Comment by alrs** [comment]
@eranelbaz Here is an example of a custom error being more identifiable in a log message using `%T`: https://go.dev/play/p/ByOlY8DGm20

**Comment by eranelbaz** [comment]
Ohh nice!
Didn't know about that option in Go
Thank you for explaining it

**Comment by alrs** [comment]
Any comments @cube2222 @marcinwyszynski ?

**Comment by alrs** [comment]
@cube2222 I don't think every `fmt.Errorf()` should be elevated to a type, but it should at least use `%w` so that `errors.Is()` has a fighting chance.

I do think that exported errors should probably all be typed, so that `%T` provides meaningful information and we don't have places in the tests (or in other people's code that uses OpenTF as a library) doing string comparisons to figure out which error just rolled in.

I mentioned the `internal/` migration in here, do you think I should create an "Internal Mirgration" issue to link to this, or is exposing the internals of `OpenTF` still some way off?

**Comment by cube2222** [comment]
> @cube2222 I don't think every fmt.Errorf() should be elevated to a type, but it should at least use %w so that errors.Is() has a fighting chance.

Yeah, definitely, wraps should use wrapping that is understood by errors.Is.

> I do think that exported errors should probably all be typed, so that %T provides meaningful information and we don't have places in the tests (or in other people's code that uses OpenTF as a library) doing string comparisons to figure out which error just rolled in.

I really don't see much value here. If the error is a const without additional info, I believe it should just be a global sentinel, like most libraries do. That will work great with errors.Is. Types makes sense to me if there's dynamic information in the error that you need to expose.

> I mentioned the internal/ migration in here, do you think I should create an "Internal Mirgration" issue to link to this, or is exposing the internals of OpenTF still some way off?

Still some way off, we'll start the discussion in 2-3 months at the earliest, I don't think it's worth creating an issue for that. Let's treat this issue as general refactor/cleanup.

**Comment by alrs** [comment]
@cube2222 Here's an example, I think the only thing this PR needs is a proper license header on the new test file.

https://github.com/opentffoundation/opentf/pull/365

**Comment by alrs** [comment]
@cube2222 Gotcha.
