### ISSUE TITLE
What are the costs of migrating from Terraform to OpenTF?

### ISSUE THREAD

**Issue by wzq2023** [opentffoundation/opentf#384]
I have internally wrapped Terraform into an orchestration service, I want know the costs of migrating from Terraform to OpenTF.

**Comment by yaronya** [comment]
Hi @wzq2023 
Once OpenTF will be released soon, migrating from Terraform should be a drop-in replacement without any custom actions from your end.

Feel free to ask more questions on our public Slack community in opentfcommunity.slack.com 🙏
