### ISSUE TITLE
roadmap repo pointers are self-referential 

### ISSUE THREAD

**Issue by keen99** [opentffoundation/opentf#398]
### OpenTF Version

```shell
n/a
```

### OpenTF Configuration Files

```hcl
...opentf config...
```

### Debug Output

...

### Expected Behavior

...

### Actual Behavior

...

### Steps to Reproduce

...

### Additional Context

the last commit to the roadmap repo:

https://github.com/opentffoundation/roadmap/commit/69e45cff08cf418f18873a69c9e01f90a177dea0

looks like it _intended_ to link to the /opentf/ issues/milestones, but instead of it linked to...itself.  where there are no issues/milestones.

and the repo is archived, so I can't comment on the commit there. :)

**Comment by roni-frantchi** [comment]
Much appreciated thanks for bringing it to our attention @keen99 !  
[Fixed](https://github.com/opentffoundation/roadmap/commit/bc02c660b93748b6494d7bf6c137ab60798f75a1) those those links now
