### ISSUE TITLE
OpenTF Slack settings hide users' other orgs

### ISSUE THREAD

**Issue by verdverm** [opentffoundation/opentf#400]
### OpenTF Version

```shell
n/a
```

### OpenTF Configuration Files

n/a

### Debug Output

![image](https://github.com/opentffoundation/opentf/assets/1390600/8c487f2d-bec4-4ecd-b314-f63cea298ab0)

### Expected Behavior

I can see all my orgs and notifications without clicking

![image](https://github.com/opentffoundation/opentf/assets/1390600/9ad7619a-ffba-493b-b348-aac962cb014a)

### Actual Behavior

![image](https://github.com/opentffoundation/opentf/assets/1390600/9dda437f-b396-4fc6-9863-ddedbc80670e)

### Steps to Reproduce

n/a

### Additional Context

I've never seen a Slack org create this condition. I cannot join the OpenTF Slack if it is going to hide my other orgs and notifications.

**Comment by omry-hay** [comment]
Hi @verdverm thanks for pointing this out, however, this is a new design by Slack that started for a new organization created in August 2023. 
You can read more about it here - https://slack.com/help/articles/16764236868755-An-overview-of-Slacks-new-design

**Comment by verdverm** [comment]
smh...

**Comment by roni-frantchi** [comment]
Thanks @verdverm .  

Like @omry-hay pointed out this is a deign Slack has been rolling out. Nothing we can do about it unfortunately - but you could provide that feedback to them.  

From their FAQ on referenced [post](https://slack.com/help/articles/16764236868755-An-overview-of-Slacks-new-design):
> **Can I switch back to the old experience?**
It's not possible to revert to the previous version of Slack. To share your feedback on the new design, open the Slack desktop app and click the  question mark icon in the top right. Then, click  Give feedback on the new design below the search field. 

I'll be closing this issue as that feedback should probably be tracked with the Slack team

**Comment by verdverm** [comment]
Is the OpenTF team open to a different chatting platform? This is unusable

**Comment by roni-frantchi** [comment]
By the way @verdverm if it helps, using keyboard shortcut helped me get passed that with all Slack organizations with the new design (and you can expect to see more of them as Slack rolls it to older organizations as well).  

So in your screenshot clicking CMD+4 would switch to OpenTF, CMD+3 for Cue and so forth.

**Comment by verdverm** [comment]
don't have a CMD key, left OpenTF community, left multiple pieces of feedback, will move my own orgs if this is actually the case

**Comment by roni-frantchi** [comment]
> don't have a CMD key

@verdverm Ctrl+no. does the exact same things. [Here](https://slack.com/help/articles/201374536-Slack-keyboard-shortcuts#windows-linux-5)'s more on that.  

> left OpenTF community, left multiple pieces of feedback, will move my own orgs if this is actually the case
Sorry to hear that @verdverm - we value that feedback and we'd love to have you join the discussions.  
We do offer other platforms for discussions, including GitHub issues and GitHub discussions.  

We've launched our chat community with Slack and as we gather more feedback we could definitely consider launching/swapping to others.

**Comment by verdverm** [comment]
Any thoughts on getting a discord going at this point too? See which one gains more traction?

I created one a few days ago, apparently out of premonition! Going to be using both for our support, but maybe not for long if Slack insists on this path forward

Looking at https://zulip.com/features/

Also https://github.com/42wim/matterbridge could be useful for taming support efforts across multiple chat platforms, let everyone choose their preferred
