### ISSUE TITLE
flakey `License Checks` checks

### ISSUE THREAD

**Issue by eranelbaz** [opentffoundation/opentf#406]
We are getting GitHub api rate limit exceeded

More details can be found in this log file
[pipelinesghubeus13.actions.githubusercontent.com_4S3JTRwu6GPB54RzNDE0wufbZC2P6Ks0uZqRow8Hx060p5Ckak__apis_pipelines_1_runs_1751_signedlogcontent_8_urlExpires=2023-09-14T12%3A56%3A43.1729041Z&urlSigningMethod=HMACV1&urlSignature=A3VOxnSX8uHQhKppDUFHkAf.txt](https://github.com/opentffoundation/opentf/files/12608955/pipelinesghubeus13.actions.githubusercontent.com_4S3JTRwu6GPB54RzNDE0wufbZC2P6Ks0uZqRow8Hx060p5Ckak__apis_pipelines_1_runs_1751_signedlogcontent_8_urlExpires.2023-09-14T12.3A56.3A43.1729041Z.urlSigningMethod.HMACV1.urlSignature.A3VOxnSX8uHQhKppDUFHkAf.txt)

**Comment by eranelbaz** [comment]
CC @pdecat

**Comment by pdecat** [comment]
Looking into it right now.

**Comment by eranelbaz** [comment]
Thank you very much @pdecat

**Comment by eranelbaz** [comment]
@pdecat LMK if you can look at it, if not I'll take it
Thank you very very much

**Comment by pdecat** [comment]
Submitted #408 to test something...

**Comment by pdecat** [comment]
It seems to be ok: https://github.com/opentffoundation/opentf/actions/runs/6185956647/job/16792599028?pr=408

**Comment by rumenvasilev** [comment]
If you commit the resulting file of `licensei cache` to the repo, it will no longer make API calls to GH API for unchanged packages (that have license).

**Comment by pdecat** [comment]
> If you commit the resulting file of `licensei cache` to the repo, it will no longer make API calls to GH API for unchanged packages (that have license).

That seems like a great idea too!
