### ISSUE TITLE
OpenTF link broken in roadmap/README.md

### ISSUE THREAD

**Issue by jeroenhabets** [opentffoundation/opentf#417]
https://github.com/opentffoundation/roadmap that is found via manifesto and Google searches shows readme:

# OpenTF Roadmap
BROKEN: Now that [OpenTF](https://github.com/opentffoundation/roadmap/blob/main/github.com/opentffoundation/opentf) is available

CORRECT: Now that [OpenTF](https://github.com/opentffoundation/opentf) is available
Source: `Now that [OpenTF](https://github.com/opentffoundation/opentf) is available`

(Logging issue here as /roadmap is archived but still found!)

**Comment by cube2222** [comment]
Thanks for creating an issue @jeroenhabets!

This is now fixed.
